### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Maden-maxi** [zefoy/ngx-fabric-wrapper#1]
When install module I get this error. But module works.
My OS Ubuntu Linux 16.04 LTS

![image](https://user-images.githubusercontent.com/17612707/33096804-eeb1bd38-cf10-11e7-8f8b-305916584034.png)

```
> canvas@1.6.7 install /home/secret/WebstormProjects/fabric/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing 'cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: 'gyp' failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-98-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/secret/WebstormProjects/fabric/node_modules/canvas
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN codelyzer@3.2.2 requires a peer of @angular/compiler@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN codelyzer@3.2.2 requires a peer of @angular/core@^2.3.1 || >=4.0.0-beta <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-fabric-wrapper@5.0.0 requires a peer of @angular/common@>=^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-fabric-wrapper@5.0.0 requires a peer of @angular/core@>=^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.7 (node_modules/canvas):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas@1.6.7 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ ngx-fabric-wrapper@5.0.0
added 160 packages in 26.116s
```

**Comment by sconix** [comment]
Yes the fabric packaging is bit weird. It includes both browser and server version. The server version needs to build the canvas library which requires devel libs which you don't seem to have installed. But the browser version naturally does not need the canvas so it works in browser. I hope they would split the package to browser and server parts at some point.

**Comment by sconix** [comment]
I have updated the readme to have the information to install with --no-optional flag which prevents installation of canvas etc. There is however another bug in fabric packaging with that. Webpack builds might have error about jsdom when the library is installed with --no-optional. This can be fixed by installing jsdom package until they fix the fabric code.
